import { jsPDF } from 'jspdf';
import { Diagnosis } from '../types';

function addWrappedText(doc: jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight: number): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  lines.forEach((line, index) => {
    doc.text(line, x, y + index * lineHeight);
  });
  return y + lines.length * lineHeight;
}

function addBulletSection(
  doc: jsPDF,
  title: string,
  items: string[],
  startY: number,
  margin: number,
  pageWidth: number
): number {
  let y = startY;

  if (y > 260) {
    doc.addPage();
    y = 20;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(27, 67, 50);
  doc.text(title, margin, y);
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);

  items.forEach((item) => {
    if (y > 275) {
      doc.addPage();
      y = 20;
    }
    y = addWrappedText(doc, `• ${item}`, margin + 2, y, pageWidth - margin * 2 - 2, 5) + 2;
  });

  return y + 4;
}

export async function exportDiagnosisPdf(diagnosis: Diagnosis, language: 'en' | 'sw'): Promise<void> {
  const isSw = language === 'sw';
  const rec = diagnosis.recommendation;
  const diseaseName = isSw ? rec.swahili.diseaseName : rec.diseaseName;
  const severity = isSw ? rec.swahili.severity : rec.severity;
  const modeLabel =
    diagnosis.analysisMode === 'ml'
      ? isSw
        ? 'Uchambuzi wa ML (TensorFlow.js)'
        : 'ML Model (TensorFlow.js)'
      : diagnosis.analysisMode === 'live-ai'
        ? isSw
          ? 'Uchambuzi wa AI wa Moja kwa Moja'
          : 'Live AI Analysis'
        : isSw
          ? 'Hali ya Onyesho (Demo)'
          : 'Demo Mode';

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const margin = 16;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 18;

  doc.setFillColor(27, 67, 50);
  doc.rect(0, 0, pageWidth, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('FieldMate', margin, 14);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(isSw ? 'Ripoti ya Uchunguzi wa Magonjwa ya Mazao' : 'Crop Disease Diagnosis Report', margin, 22);

  y = 38;
  doc.setTextColor(27, 67, 50);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(diseaseName, margin, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  y = addWrappedText(
    doc,
    `${isSw ? 'Mmea' : 'Crop'}: ${diagnosis.cropType}  |  ${isSw ? 'Uhakika' : 'Confidence'}: ${diagnosis.confidence}%  |  ${isSw ? 'Hatari' : 'Severity'}: ${severity}`,
    margin,
    y,
    pageWidth - margin * 2,
    5
  );
  y += 2;
  y = addWrappedText(
    doc,
    `${isSw ? 'Tarehe' : 'Date'}: ${new Date(diagnosis.timestamp).toLocaleString(isSw ? 'sw-TZ' : 'en-US')}  |  ${modeLabel}`,
    margin,
    y,
    pageWidth - margin * 2,
    5
  );

  if (diagnosis.imageUrl?.startsWith('data:image')) {
    try {
      const format = diagnosis.imageUrl.includes('png') ? 'PNG' : 'JPEG';
      const imgWidth = 70;
      const imgHeight = 52;
      if (y + imgHeight > 270) {
        doc.addPage();
        y = 20;
      }
      doc.addImage(diagnosis.imageUrl, format, margin, y + 4, imgWidth, imgHeight);
      y += imgHeight + 12;
    } catch {
      y += 4;
    }
  } else {
    y += 6;
  }

  y = addBulletSection(
    doc,
    isSw ? 'Dalili' : 'Symptoms',
    isSw ? rec.swahili.symptoms : rec.symptoms,
    y,
    margin,
    pageWidth
  );
  y = addBulletSection(
    doc,
    isSw ? 'Sababu' : 'Causes',
    isSw ? rec.swahili.causes : rec.causes,
    y,
    margin,
    pageWidth
  );
  y = addBulletSection(
    doc,
    isSw ? 'Matibabu' : 'Treatment',
    isSw ? rec.swahili.treatment : rec.treatment,
    y,
    margin,
    pageWidth
  );
  y = addBulletSection(
    doc,
    isSw ? 'Kinga' : 'Prevention',
    isSw ? rec.swahili.prevention : rec.prevention,
    y,
    margin,
    pageWidth
  );

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.text(
    isSw
      ? 'Imetolewa na FieldMate — msaidizi wa kilimo kwa wakulima wadogo.'
      : 'Generated by FieldMate — crop advisory for smallholder farmers.',
    margin,
    footerY
  );

  const safeName = diseaseName.replace(/[^\w\s-]/g, '').trim().replace(/\s+/g, '-').slice(0, 40);
  doc.save(`FieldMate-${diagnosis.cropType}-${safeName || 'report'}.pdf`);
}
